version: '3'

services:
    nginx:
        image: nginx:latest
        volumes:
            - ./:/var/www
            - ./_docker/nginx/conf.d/:/etc/nginx/conf.d
        ports:
            - 8026:80
        container_name: ${APP_NAME}_nginx
        depends_on:
            - app
    app:
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        volumes:
            - ./:/var/www/
        container_name: ${APP_NAME}_app
        depends_on:
            - db
    db:
        image: postgres:latest
        restart: always
        environment:
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD}'
        volumes:
            - pgdata:/var/lib/postgresql/data
        ports:
            - 5449:5432
        container_name: ${APP_NAME}_db
volumes:
    pgdata:
